// <auto-generated />
using System;
using Art2026.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Art2026.Migrations
{
    [DbContext(typeof(ArtContext))]
    [Migration("20260201161857_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Art2026.Models.Exhibition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Artists")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("ClosesAt")
                        .HasColumnType("time(6)");

                    b.Property<int>("ManifestationDayId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("OpensAt")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("ManifestationDayId");

                    b.ToTable("Exhibitions");
                });

            modelBuilder.Entity("Art2026.Models.Manifestation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DiscountEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaxVisitorsPerDay")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PricePainting")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PricePhotography")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Manifestations");
                });

            modelBuilder.Entity("Art2026.Models.ManifestationDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ManifestationId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ManifestationId");

                    b.ToTable("ManifestationDays");
                });

            modelBuilder.Entity("Art2026.Models.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("InvalidatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UsedByRegistrationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.HasIndex("UsedByRegistrationId");

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("Art2026.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Address2")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumberOfPersons")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Profession")
                        .HasColumnType("longtext");

                    b.Property<int?>("UsedPromoCodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique();

                    b.HasIndex("UsedPromoCodeId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("Art2026.Models.RegistrationDay", b =>
                {
                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<int>("ManifestationDayId")
                        .HasColumnType("int");

                    b.HasKey("RegistrationId", "ManifestationDayId");

                    b.HasIndex("ManifestationDayId");

                    b.ToTable("RegistrationDays");
                });

            modelBuilder.Entity("Art2026.Models.Exhibition", b =>
                {
                    b.HasOne("Art2026.Models.ManifestationDay", "ManifestationDay")
                        .WithMany("Exhibitions")
                        .HasForeignKey("ManifestationDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManifestationDay");
                });

            modelBuilder.Entity("Art2026.Models.ManifestationDay", b =>
                {
                    b.HasOne("Art2026.Models.Manifestation", "Manifestation")
                        .WithMany("Days")
                        .HasForeignKey("ManifestationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifestation");
                });

            modelBuilder.Entity("Art2026.Models.PromoCode", b =>
                {
                    b.HasOne("Art2026.Models.Registration", "Registration")
                        .WithOne("GeneratedPromoCode")
                        .HasForeignKey("Art2026.Models.PromoCode", "RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Art2026.Models.Registration", "UsedByRegistration")
                        .WithMany()
                        .HasForeignKey("UsedByRegistrationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Registration");

                    b.Navigation("UsedByRegistration");
                });

            modelBuilder.Entity("Art2026.Models.Registration", b =>
                {
                    b.HasOne("Art2026.Models.PromoCode", "UsedPromoCode")
                        .WithMany()
                        .HasForeignKey("UsedPromoCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsedPromoCode");
                });

            modelBuilder.Entity("Art2026.Models.RegistrationDay", b =>
                {
                    b.HasOne("Art2026.Models.ManifestationDay", "ManifestationDay")
                        .WithMany("RegistrationDays")
                        .HasForeignKey("ManifestationDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Art2026.Models.Registration", "Registration")
                        .WithMany("RegistrationDays")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManifestationDay");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Art2026.Models.Manifestation", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("Art2026.Models.ManifestationDay", b =>
                {
                    b.Navigation("Exhibitions");

                    b.Navigation("RegistrationDays");
                });

            modelBuilder.Entity("Art2026.Models.Registration", b =>
                {
                    b.Navigation("GeneratedPromoCode");

                    b.Navigation("RegistrationDays");
                });
#pragma warning restore 612, 618
        }
    }
}
